spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    hikari:
      username: root
      password: xiaojian520
      driver-class-name: com.mysql.cj.jdbc.Driver
  #redis配置
  redis:
    host: 127.0.0.1           #192.168.0.109
    port: 6379
    jedis:   #jedis的配置可以省
      pool:
        max-idle: 20      # 连接池中的最大空闲连接
        min-idle: 1
        max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 60000   #连接池最大阻塞等待时间
    database: 0   #这里不配置默认就是0号数据库
    #集群
    #cluster:
    #以后连接池的配置要用lettuce，因为redis连接工厂中很多类已经不存在了，连接一定不成功
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: pro3 #在nacos Server上的名字

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp


mybatis: #设置mybatis包扫描简称
  #配置mybatis配置文件的路径 config-location: classpath:mybatis.xml
  type-aliases-package: com.mynb.pojo
  #mapper-locations: classpath:mybatis/com/**/dao/*.xml #映射文件的位置
server:
  port: 8888

logging: #设置日志级别
  level:
    root: debug
#pageHelper插件配置
pagehelper:
  helper-dialect: mysql   #数据库连接
  reasonable: true        #分页合理化参数